import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  projects,
  home,
}: {
  children: React.ReactNode;
  projects: React.ReactNode;
  home: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100`}>
        <div className="bg-custom-bg bg-no-repeat bg-right bg-contain h-screen pt-6">
          <Navbar />
          {children}
          {home}
        </div>
        <div className=" h-[100vh]">{projects}</div>
      </body>
    </html>
  );
}
